"""add redirect count and last redirect

Revision ID: 4b0bd285feb4
Revises: c29fe8ae52ae
Create Date: 2025-12-25 10:46:35.692350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b0bd285feb4"
down_revision: Union[str, Sequence[str], None] = "c29fe8ae52ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "short_urls",
        sa.Column("redirect_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "short_urls",
        sa.Column("last_redirect_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("short_urls", "last_redirect_at")
    op.drop_column("short_urls", "redirect_count")
    # ### end Alembic commands ###
